version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=YOurR00tPAsswOrd
    volumes:
      - /home/rterrero/mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped